packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^24
  '@types/react': ^19
  '@types/react-dom': ^19
  neverthrow: ^8
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5
  vitest: ^3
  zod: ^4

allowBuilds:
  cpu-features: false
  esbuild: true
  lefthook: true
  protobufjs: false
  sharp: false
  ssh2: false
