packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^24
  neverthrow: ^8
  typescript: ^5
  vitest: ^3
  zod: ^4

allowBuilds:
  cpu-features: false
  esbuild: true
  lefthook: true
  protobufjs: false
  ssh2: false
